docker-base-build/base-requirements.txt

Fixes a bug in the return from sensor_detail.

Update to katportalclient 0.2.1

---

build-docker-image.sh

The user of build-docker-image must pass --push-external to the script,
set DOCKER_EXTERNAL_REGISTRY to the registry prefix (e.g.
quay.io/ska-sa) and have set up the credentials.

Support for pushing to an external registry

---

Jenkinsfile
docker-base-build/Dockerfile
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile
docker-base-runtime/Dockerfile

Also replaced deprecated MAINTAINER line in Dockerfile with a label, and
updated the email address. This new address still needs to be set up.

Push docker-base-{build, runtime} to quay.io

---

docker-base-build/base-requirements.txt

Github reports a CVE in the prior version.

Bump pillow to the latest version

---

docker-base-build/base-requirements.txt

This is needed by katdal in the impending PR ska-sa/katdal#273.

Add PyJWT to base requirements

---

docker-base-build/base-requirements.txt

Add cityhash to base requirements

---

docker-base-build/base-requirements.txt

Needed to support src-layout packages.

Bump katversion to 1.0

---

docker-base-build/base-requirements.txt

It's now used by a few SDP projects.

Add astropy to base requirements

---

docker-base-build/base-requirements.txt

Upgrade to PyJWT 2.x for katdal

---

docker-base-build/base-requirements.txt
docker-base-gpu-build/requirements.txt
docker-base-runtime/Dockerfile

All are bumped to the latest except for one or two which are documented
in the comments.

Bump versions in base-requirements.txt

---

docker-base-build/install_pinned.py
docker-base-build/test_install_pinned.py

Allow combining URLs with version upper bounds

---

docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile

This is needed to work with RTX 30xx GPUs.

Update CUDA to 11.3.1

---

docker-base-build/base-requirements.txt
docker-base-build/pre-requirements.txt

Mostly this is to update pip to keep dependabot happy, but I bumped all
the packages in pre-requirements, and also where those packages appear
in base-requirements I updated them to match.

Bump versions of everything in pre-requirements.txt

---

docker-base-build/base-requirements.txt

This version supports bulk sensor sampling.

Bump aiokatcp to version 1.1

---

docker-base-build/base-requirements.txt

3.8.0 introduced a feature that I want to use for unit testing in
katsdpcontroller.

Bump aiohttp to the latest version

---

docker-base-build/base-requirements.txt

This will allow the master controller to use bulk sensor sampling.

Bump aiokatcp to the latest version

---

docker-base-build/base-requirements.txt

This will simplify adding it as a 'local' pre-commit hook in other packages.

Add mypy to base-requirements

---

docker-base-build/base-requirements.txt

It's about to become a dependency of katsdpsigproc.

Add importlib-resources to base-requirements

---

build-docker-image.sh

If set, images will be pushed there in addition to DOCKER_REGISTRY.
Note: https://github.com/ska-sa/katsdpjenkins/pull/24 needs to be merged first.

Add support for DOCKER_REGISTRY2 in build-docker-image.sh

---

docker-base-build/Dockerfile
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile

Update KATSDPDOCKERBASE_REGISTRY to point at harbor

---

docker-base-build/base-requirements.txt

Sphinx and friends causing trouble.

Upgrade requirements necessary for doc generation.
