ska-sa/katsdpdockerbase

build-docker-image.sh
docker-base-build/Dockerfile
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile

The Dockerfiles are parametrised with the path to the registry, although
still defaulting to sdp-docker-registry. In future we could change
replace it with just a Dockerhub username for Dockerhub to build the
images. The Jenkins builder script takes the environment variable
DOCKER_REGISTRY (set in the Jenkins server configuration) and passes it
through.
As an added bonus, the build script also passes the tag being built, and
the Dockerfiles use that to specify the base image. This will fix the
problem of building branches of katsdpdockerbase itself, where
docker-base-build will be FROM docker-base-runtime:latest instead of
FROM docker-base-runtime:branch-being-built.

Make it easier to build against an alternate registry

---

docker-base-build/base-requirements.txt

It contains a fix that should help prevent ingest running out of memory.

Use spead2 2.0.0 (on new enough Python versions)

---

docker-base-build/Dockerfile
docker-base-runtime/Dockerfile

Fixes SPR1-329 (crash when run on lab machines). I've test this on site with katsdpingest and katcbfsim and it appears to be working with the older host driver/kernel used there.
I removed libvma because it created problems with the install (tried to use update-rc.d to enable a non-existent vma service) and we're not using it (it was used back when we ran ptuse inside SDP).

Upgrade to MLNX OFED 4.7

---

docker-base-runtime/run-and-cleanup

The former allows the directory to be created if it does not already
exist, and the latter sets it as TMPDIR. Together they make it easier to
run a task and have it place temporary files in a specific location
(e.g. on a particular mount) without modifying it.

Add --create and --tmp to run_and_cleanup

---

docker-base-build/Dockerfile
docker-base-build/base-requirements.txt
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile
docker-base-runtime/Dockerfile

Now that Python 2 is EOL and most of our containers have migrated or are in the process of migrating, we can remove all the Python 2 baggage. I propose that we fork master into a `python2` legacy branch that will live only to support the last few containers, then merge this one and do all updates here.
I've avoided updating any versions of Python packages, although there are a number that can be upgraded to versions that have dropped Python 2 support.
I've marked this draft because we shouldn't merge before we've split out the python2 branch.

Drop Python 2 support from katsdpdockerbase

---

docker-base-build/base-requirements.txt

The biggest difference actually seems to be that it now requires ujson
2.x, which doesn't truncate floats.

Update katportalclient to new release

---

docker-base-build/base-requirements.txt

This will make it easier to use pytest for testing in packages (and also needed for ska-sa/katsdpcookiecutter#1).

Add pytest to base-requirements

---

docker-base-build/base-requirements.txt

Add strict-rfc3339 to requirements

---

docker-base-gpu-runtime/Dockerfile

When building a branch, it was copying the CUDA installation from
latest instead of the branch.

Fix image reference from which to copy CUDA

---

docker-base-build/Dockerfile
docker-base-build/base-requirements.txt
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile
docker-base-runtime/Dockerfile
docker-base-runtime/capambel.c

This makes it play nice with spead2 3.x.
To support newer mlx5 kernel modules, add a utility program (capambel) which can set ambient capabilities. Child images that need such capabilities (currently just katcbfsim, since it doesn't seem to be needed for receive) use setcap to grant capambel the capability. An alternative would be to just grant the Python binary the capability directly. I'm not sure which approach is better, so feedback is welcome. Having a separate utility means that
(a) it can be used to run other tools inside the container (e.g. spead2_recv binary);
(b) if the capability isn't present for some reason (e.g. if the Docker storage backend doesn't support capabilities), capambel will fail early, rather than a somewhat cryptic error when trying to capture-start.
The …

Use upstream rdma-core instead of MLNX-OFED 4.x

---

docker-base-build/Dockerfile
docker-base-build/base-requirements.txt
docker-base-gpu-build/Dockerfile
docker-base-gpu-runtime/Dockerfile
docker-base-runtime/Dockerfile

Most of the updates are to bump to versions that work on Ubuntu 20.04 or Python 3.8 (including CUDA). I also had to remove KERN because there isn't a version supporting 20.04 yet.
Don't merge yet: there are a number of other images that need matching changes to be merged at the same time.

Update to Ubuntu 20.04

---

docker-base-build/base-requirements.txt

I had removed it because katpoint master no longer depends on it, but
katsdpdata installs katpoint==0.9 which still does.

Add back a default version for pyephem

---

docker-base-build/base-requirements.txt

Newer versions suffer from https://github.com/numba/numba/issues/6819,
which is affecting katsdpcal.

Downgrade numba to 0.51.2

---

docker-base-build/base-requirements.txt

To avoid https://github.com/dask/dask/issues/7402. See also SPR1-847.

Downgrade dask to 2.30

---

docker-base-build/base-requirements.txt

To avoid being impacted by https://github.com/dask/dask/issues/7632.

Downgrade dask to 2.27

---

docker-base-gpu-runtime/Dockerfile

This was broken by #71, which upgraded CUDA to 11.3.1 and also set
`NVIDIA_REQUIRE_CUDA>=11.3` in the runtime image. The meaning of this
setting is a bit murky, but I believe that each driver release reports a
version of CUDA is supports, and this is compared before starting the
container. The 460.39 drivers deployed on site advertise support for
CUDA 11.2, but according to the CUDA release notes, CUDA 11.0 to 11.4
all have the same requirement: 450.80.02 or later.
Since all CUDA 11 versions have the same minimum requirement, I've
changed NVIDIA_REQUIRE_CUDA to 11.0 (which matches what was in the build
image).

Fix for NVIDIA 460.xx drivers

---

docker-base-build/install_pinned.py

Given `package==version` in a defaults file and
`package @ git+https://...` in a requirements file, install_pinned.py was refusing to proceed. Relax the logic so that the default is ignored in this case.

Allow URL in requirements to override default pin

---

docker-base-build/base-requirements.txt

This contains features that are due to be used in katsdpcontroller, but also some bugfixes so all packages might as well benefit.

Bump aiokatcp to 1.5.0

---

docker-base-build/base-requirements.txt
docker-base-build/pre-requirements.txt

This should subsume some of the PRs that Dependabot opened. I left alone pyjwt, numpy and dask, since they're high-risk updates and I don't want them to be my problem.
markupsafe wasn't directly flagged by dependabot, but it flagged a dependent in a downstream repo that needs a newer markupsafe to be upgraded.

Bump some vulnerable versions in base-requirements

---

docker-base-build/base-requirements.txt

It needs an updated jinja2 to work, and that in turn requires an update to aiohttp_jinja2. It's turning into more interactions with SDP packages than I want to be responsible for.

Roll back an update to markupsafe

---

docker-base-build/base-requirements.txt

This is still some minor fallout of the katsdptelstate 0.13 release.
As discussed in ska-sa/katsdpimager#124, it is useful to pull lupa into docker base as it is a dependency of `fakeredis[lua]`, and the two packages typically go hand-in-hand in our packages.
Currently the two are used in the tests of `katsdptelstate` and `katsdpimager`. This change avoids updating lupa in *two* places in future (the minimum to make this beneficial :-) ).

SPR1-2766: Add lupa==1.14.1 to docker base

---

docker-base-build/Dockerfile

This was out-of-date, see https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
Issue was originally picked up during discussion on https://github.com/ska-sa/katsdpinfrastructure/pull/835
Relates to NGC-1149.

Fix github SSH public key

---

build-docker-image.sh

The deprecated label-schema.org labels are left in place for compatibility, but the new opencontainers.org labels are added as well.

Add OCI annotation labels

---

docker-base-build/base-requirements.txt

redis was recently updated from 4.5.1 to 4.6.0 in base-reqs. This PR (https://github.com/redis/redis-py/pull/2583), included within that update, added a disconnect_on_error parameter to read_response(), which is causing tests to fail in katsdptelstate. Update fakeredis to a newer version to resolve this. https://skaafrica.atlassian.net/browse/SPR1-3127

SPR1-3127 update fakeredis to match newer redis
